# https://pnpm.io/pnpm-workspace_yaml
packages:
  - 'apps/*'
  - 'packages/*'

allowBuilds:
  # Required by Content Collections file watching
  '@parcel/watcher': true
  # Required by Vite and Vitest tooling
  esbuild: true

# Avoid auto-installing before clean scripts that remove node_modules
verifyDepsBeforeRun: false
