/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HelpIndexRouteImport } from './routes/help/index'
import { Route as SitesPomodorocatIndexRouteImport } from './routes/sites.pomodorocat/index'
import { Route as LegalTermsIndexRouteImport } from './routes/legal.terms/index'
import { Route as LegalPrivacyIndexRouteImport } from './routes/legal.privacy/index'
import { Route as HelpAppStoreIndexRouteImport } from './routes/help.app-store/index'
import { Route as SitesPomodorocatSitemapDotxmlRouteImport } from './routes/sites.pomodorocat/sitemap[.]xml'
import { Route as SitesPomodorocatRobotsDottxtRouteImport } from './routes/sites.pomodorocat/robots[.]txt'
import { Route as SitesPomodorocatBlogIndexRouteImport } from './routes/sites.pomodorocat.blog/index'
import { Route as SitesPomodorocatBlogSlugIndexRouteImport } from './routes/sites.pomodorocat.blog.$slug/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpIndexRoute = HelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesPomodorocatIndexRoute = SitesPomodorocatIndexRouteImport.update({
  id: '/sites/pomodorocat/',
  path: '/sites/pomodorocat/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsIndexRoute = LegalTermsIndexRouteImport.update({
  id: '/legal/terms/',
  path: '/legal/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyIndexRoute = LegalPrivacyIndexRouteImport.update({
  id: '/legal/privacy/',
  path: '/legal/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpAppStoreIndexRoute = HelpAppStoreIndexRouteImport.update({
  id: '/help/app-store/',
  path: '/help/app-store/',
  getParentRoute: () => rootRouteImport,
} as any)
const SitesPomodorocatSitemapDotxmlRoute =
  SitesPomodorocatSitemapDotxmlRouteImport.update({
    id: '/sites/pomodorocat/sitemap.xml',
    path: '/sites/pomodorocat/sitemap.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitesPomodorocatRobotsDottxtRoute =
  SitesPomodorocatRobotsDottxtRouteImport.update({
    id: '/sites/pomodorocat/robots.txt',
    path: '/sites/pomodorocat/robots.txt',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitesPomodorocatBlogIndexRoute =
  SitesPomodorocatBlogIndexRouteImport.update({
    id: '/sites/pomodorocat/blog/',
    path: '/sites/pomodorocat/blog/',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitesPomodorocatBlogSlugIndexRoute =
  SitesPomodorocatBlogSlugIndexRouteImport.update({
    id: '/sites/pomodorocat/blog/$slug/',
    path: '/sites/pomodorocat/blog/$slug/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/help/': typeof HelpIndexRoute
  '/sites/pomodorocat/robots.txt': typeof SitesPomodorocatRobotsDottxtRoute
  '/sites/pomodorocat/sitemap.xml': typeof SitesPomodorocatSitemapDotxmlRoute
  '/help/app-store/': typeof HelpAppStoreIndexRoute
  '/legal/privacy/': typeof LegalPrivacyIndexRoute
  '/legal/terms/': typeof LegalTermsIndexRoute
  '/sites/pomodorocat/': typeof SitesPomodorocatIndexRoute
  '/sites/pomodorocat/blog/': typeof SitesPomodorocatBlogIndexRoute
  '/sites/pomodorocat/blog/$slug/': typeof SitesPomodorocatBlogSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/help': typeof HelpIndexRoute
  '/sites/pomodorocat/robots.txt': typeof SitesPomodorocatRobotsDottxtRoute
  '/sites/pomodorocat/sitemap.xml': typeof SitesPomodorocatSitemapDotxmlRoute
  '/help/app-store': typeof HelpAppStoreIndexRoute
  '/legal/privacy': typeof LegalPrivacyIndexRoute
  '/legal/terms': typeof LegalTermsIndexRoute
  '/sites/pomodorocat': typeof SitesPomodorocatIndexRoute
  '/sites/pomodorocat/blog': typeof SitesPomodorocatBlogIndexRoute
  '/sites/pomodorocat/blog/$slug': typeof SitesPomodorocatBlogSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/help/': typeof HelpIndexRoute
  '/sites/pomodorocat/robots.txt': typeof SitesPomodorocatRobotsDottxtRoute
  '/sites/pomodorocat/sitemap.xml': typeof SitesPomodorocatSitemapDotxmlRoute
  '/help/app-store/': typeof HelpAppStoreIndexRoute
  '/legal/privacy/': typeof LegalPrivacyIndexRoute
  '/legal/terms/': typeof LegalTermsIndexRoute
  '/sites/pomodorocat/': typeof SitesPomodorocatIndexRoute
  '/sites/pomodorocat/blog/': typeof SitesPomodorocatBlogIndexRoute
  '/sites/pomodorocat/blog/$slug/': typeof SitesPomodorocatBlogSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/help/'
    | '/sites/pomodorocat/robots.txt'
    | '/sites/pomodorocat/sitemap.xml'
    | '/help/app-store/'
    | '/legal/privacy/'
    | '/legal/terms/'
    | '/sites/pomodorocat/'
    | '/sites/pomodorocat/blog/'
    | '/sites/pomodorocat/blog/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/help'
    | '/sites/pomodorocat/robots.txt'
    | '/sites/pomodorocat/sitemap.xml'
    | '/help/app-store'
    | '/legal/privacy'
    | '/legal/terms'
    | '/sites/pomodorocat'
    | '/sites/pomodorocat/blog'
    | '/sites/pomodorocat/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/help/'
    | '/sites/pomodorocat/robots.txt'
    | '/sites/pomodorocat/sitemap.xml'
    | '/help/app-store/'
    | '/legal/privacy/'
    | '/legal/terms/'
    | '/sites/pomodorocat/'
    | '/sites/pomodorocat/blog/'
    | '/sites/pomodorocat/blog/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  HelpIndexRoute: typeof HelpIndexRoute
  SitesPomodorocatRobotsDottxtRoute: typeof SitesPomodorocatRobotsDottxtRoute
  SitesPomodorocatSitemapDotxmlRoute: typeof SitesPomodorocatSitemapDotxmlRoute
  HelpAppStoreIndexRoute: typeof HelpAppStoreIndexRoute
  LegalPrivacyIndexRoute: typeof LegalPrivacyIndexRoute
  LegalTermsIndexRoute: typeof LegalTermsIndexRoute
  SitesPomodorocatIndexRoute: typeof SitesPomodorocatIndexRoute
  SitesPomodorocatBlogIndexRoute: typeof SitesPomodorocatBlogIndexRoute
  SitesPomodorocatBlogSlugIndexRoute: typeof SitesPomodorocatBlogSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/': {
      id: '/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof HelpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/pomodorocat/': {
      id: '/sites/pomodorocat/'
      path: '/sites/pomodorocat'
      fullPath: '/sites/pomodorocat/'
      preLoaderRoute: typeof SitesPomodorocatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms/': {
      id: '/legal/terms/'
      path: '/legal/terms'
      fullPath: '/legal/terms/'
      preLoaderRoute: typeof LegalTermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy/': {
      id: '/legal/privacy/'
      path: '/legal/privacy'
      fullPath: '/legal/privacy/'
      preLoaderRoute: typeof LegalPrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/app-store/': {
      id: '/help/app-store/'
      path: '/help/app-store'
      fullPath: '/help/app-store/'
      preLoaderRoute: typeof HelpAppStoreIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/pomodorocat/sitemap.xml': {
      id: '/sites/pomodorocat/sitemap.xml'
      path: '/sites/pomodorocat/sitemap.xml'
      fullPath: '/sites/pomodorocat/sitemap.xml'
      preLoaderRoute: typeof SitesPomodorocatSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/pomodorocat/robots.txt': {
      id: '/sites/pomodorocat/robots.txt'
      path: '/sites/pomodorocat/robots.txt'
      fullPath: '/sites/pomodorocat/robots.txt'
      preLoaderRoute: typeof SitesPomodorocatRobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/pomodorocat/blog/': {
      id: '/sites/pomodorocat/blog/'
      path: '/sites/pomodorocat/blog'
      fullPath: '/sites/pomodorocat/blog/'
      preLoaderRoute: typeof SitesPomodorocatBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sites/pomodorocat/blog/$slug/': {
      id: '/sites/pomodorocat/blog/$slug/'
      path: '/sites/pomodorocat/blog/$slug'
      fullPath: '/sites/pomodorocat/blog/$slug/'
      preLoaderRoute: typeof SitesPomodorocatBlogSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  HelpIndexRoute: HelpIndexRoute,
  SitesPomodorocatRobotsDottxtRoute: SitesPomodorocatRobotsDottxtRoute,
  SitesPomodorocatSitemapDotxmlRoute: SitesPomodorocatSitemapDotxmlRoute,
  HelpAppStoreIndexRoute: HelpAppStoreIndexRoute,
  LegalPrivacyIndexRoute: LegalPrivacyIndexRoute,
  LegalTermsIndexRoute: LegalTermsIndexRoute,
  SitesPomodorocatIndexRoute: SitesPomodorocatIndexRoute,
  SitesPomodorocatBlogIndexRoute: SitesPomodorocatBlogIndexRoute,
  SitesPomodorocatBlogSlugIndexRoute: SitesPomodorocatBlogSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
