// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	getAppInfo: () => __TAURI_INVOKE<AppInfoDto>("get_app_info"),
	showMainWindow: () => typedError<null, string>(__TAURI_INVOKE("show_main_window")),
	showMainWindowAtPath: (path: string) => typedError<null, string>(__TAURI_INVOKE("show_main_window_at_path", { path })),
	showCatWindow: () => typedError<null, string>(__TAURI_INVOKE("show_cat_window")),
	showSettingsWindow: () => typedError<null, string>(__TAURI_INVOKE("show_settings_window")),
	showSettingsWindowAtPath: (path: string) => typedError<null, string>(__TAURI_INVOKE("show_settings_window_at_path", { path })),
	showActivityWindow: () => typedError<null, string>(__TAURI_INVOKE("show_activity_window")),
	showActivityWindowAtSession: (sessionId: number) => typedError<null, string>(__TAURI_INVOKE("show_activity_window_at_session", { sessionId })),
	hideMainWindow: () => typedError<null, string>(__TAURI_INVOKE("hide_main_window")),
	navigateMainWindowToPath: (path: string) => typedError<null, string>(__TAURI_INVOKE("navigate_main_window_to_path", { path })),
	hideCatWindow: () => typedError<null, string>(__TAURI_INVOKE("hide_cat_window")),
	hideSettingsWindow: () => typedError<null, string>(__TAURI_INVOKE("hide_settings_window")),
	navigateSettingsWindowToPath: (path: string) => typedError<null, string>(__TAURI_INVOKE("navigate_settings_window_to_path", { path })),
	restartApp: () => __TAURI_INVOKE<void>("restart_app"),
	quitApp: () => __TAURI_INVOKE<void>("quit_app"),
	installUpdate: () => typedError<null, string>(__TAURI_INVOKE("install_update")),
	getSettings: () => __TAURI_INVOKE<AppSettings>("get_settings"),
	setSettings: (settings: AppSettings) => typedError<null, string>(__TAURI_INVOKE("set_settings", { settings })),
	clearHistory: () => typedError<null, string>(__TAURI_INVOKE("clear_history")),
	resetSettings: () => typedError<null, string>(__TAURI_INVOKE("reset_settings")),
	getDataDirectoryPath: () => __TAURI_INVOKE<string>("get_data_directory_path"),
	openDataDirectory: () => typedError<null, string>(__TAURI_INVOKE("open_data_directory")),
	getTimer: () => __TAURI_INVOKE<TimerDto>("get_timer"),
	startTimer: (input: {
	intention?: string | null,
	profileIds?: number[] | null,
	blockThreshold?: BlockThreshold | null,
} | null) => typedError<null, string>(__TAURI_INVOKE("start_timer", { input })),
	pauseTimer: () => typedError<null, string>(__TAURI_INVOKE("pause_timer")),
	resumeTimer: () => typedError<null, string>(__TAURI_INVOKE("resume_timer")),
	resetTimer: () => typedError<null, string>(__TAURI_INVOKE("reset_timer")),
	/**
	 *  Complete the current session and advance to the next in the Pomodoro sequence (work↔break).
	 *  When the next session is work, intention and profile_ids may be provided.
	 */
	advancePomodoroTimer: (input: {
	intention?: string | null,
	profileIds?: number[] | null,
	blockThreshold?: BlockThreshold | null,
} | null) => typedError<null, string>(__TAURI_INVOKE("advance_pomodoro_timer", { input })),
	/**  Advance to the specified next Progressive session type and duration. */
	advanceProgressiveTimer: (sessionType: ProgressiveSessionType, durationSeconds: number, input: {
	intention?: string | null,
	profileIds?: number[] | null,
	blockThreshold?: BlockThreshold | null,
} | null) => typedError<null, string>(__TAURI_INVOKE("advance_progressive_timer", { sessionType, durationSeconds, input })),
	/**
	 *  Complete the current session and reset timer.
	 *  Like reset, but marks session as completed instead of cancelled.
	 */
	completeTimer: () => typedError<null, string>(__TAURI_INVOKE("complete_timer")),
	setTimerDuration: (minutes: number) => typedError<null, string>(__TAURI_INVOKE("set_timer_duration", { minutes })),
	/**  Get current active app or window by querying the OS. */
	getCurrentActivity: (params: GetCurrentActivityParams) => typedError<CurrentActivityDto, string>(__TAURI_INVOKE("get_current_activity", { params })),
	/**
	 *  Get past activities within a time range.
	 *  Returns window-level activities if available, otherwise falls back to app-level activities.
	 */
	getWindowActivities: (params: GetWindowActivitiesParams) => typedError<WindowActivityDto[], string>(__TAURI_INVOKE("get_window_activities", { params })),
	getTodayFocusSeconds: () => typedError<number, string>(__TAURI_INVOKE("get_today_focus_seconds")),
	getSessions: (startedAfter: number | null, startedBefore: number | null, limit: number | null, minDurationSecs: number | null) => typedError<SessionSummaryDto[], string>(__TAURI_INVOKE("get_sessions", { startedAfter, startedBefore, limit, minDurationSecs })),
	getMostRecentSessionId: (startedAfter: number | null, startedBefore: number | null, minDurationSecs: number | null) => typedError<number | null, string>(__TAURI_INVOKE("get_most_recent_session_id", { startedAfter, startedBefore, minDurationSecs })),
	getSession: (sessionId: number) => typedError<{
	id: number,
	sessionType: string,
	status: SessionStatus,
	plannedSeconds: number,
	actualSeconds: number | null,
	intention: string | null,
	startedAt: number,
	endedAt: number | null,
	events: SessionEventDto[],
	stats: SessionStatsDto,
} | null, string>(__TAURI_INVOKE("get_session", { sessionId })),
	/**  Get the most recent completed work session. */
	getLastWorkSession: (minDurationSecs: number | null) => typedError<{
	id: number,
	sessionType: string,
	status: SessionStatus,
	plannedSeconds: number,
	actualSeconds: number | null,
	intention: string | null,
	startedAt: number,
	endedAt: number | null,
	events: SessionEventDto[],
	stats: SessionStatsDto,
} | null, string>(__TAURI_INVOKE("get_last_work_session", { minDurationSecs })),
	/**  Check if accessibility permission is granted. */
	isAccessibilityGranted: () => __TAURI_INVOKE<boolean>("is_accessibility_granted"),
	/**  Open System Settings to Accessibility pane. */
	openAccessibilitySettings: () => __TAURI_INVOKE<void>("open_accessibility_settings"),
	/**  Check if input monitoring permission is granted. */
	isInputMonitoringGranted: () => __TAURI_INVOKE<boolean>("is_input_monitoring_granted"),
	/**  Open System Settings to Input Monitoring pane. */
	openInputMonitoringSettings: () => __TAURI_INVOKE<void>("open_input_monitoring_settings"),
	/**  Search for apps and websites. */
	search: (params: SearchParams) => typedError<SearchResultDto[], string>(__TAURI_INVOKE("search", { params })),
	/**  Refresh the search cache (reloads apps from system). */
	refreshSearchCache: () => typedError<null, string>(__TAURI_INVOKE("refresh_search_cache")),
	/**  Play a sound effect. */
	playSound: (id: SoundId) => typedError<null, string>(__TAURI_INVOKE("play_sound", { id })),
	getFocusProfiles: () => typedError<FocusProfileDto[], string>(__TAURI_INVOKE("get_focus_profiles")),
	getFocusProfile: (id: number) => typedError<{
	id: number,
	name: string,
	color: string | null,
	enabled: boolean,
	categories: CategoryAssignmentDto[],
	activations: FocusProfileActivationDto[],
	createdAt: number,
} | null, string>(__TAURI_INVOKE("get_focus_profile", { id })),
	createFocusProfile: (name: string, color: string | null, enabled: boolean, categories: FocusProfileCategoryParams[], activations: FocusProfileActivationParams[]) => typedError<FocusProfileDto, string>(__TAURI_INVOKE("create_focus_profile", { name, color, enabled, categories, activations })),
	updateFocusProfile: (id: number, name: string, color: string | null, enabled: boolean, categories: FocusProfileCategoryParams[], activations: FocusProfileActivationParams[]) => typedError<FocusProfileDto, string>(__TAURI_INVOKE("update_focus_profile", { id, name, color, enabled, categories, activations })),
	deleteFocusProfile: (id: number) => typedError<null, string>(__TAURI_INVOKE("delete_focus_profile", { id })),
	/**
	 *  Returns all enabled profiles with their activation status for session setup.
	 * 
	 *  - AlwaysOn: active always_on activation — shown, not removable
	 *  - PreSelected: active pre_selected activation — shown, removable
	 *  - Manual: no active activation — user adds manually
	 * 
	 *  `session_type`: None = no session type filter, show all.
	 */
	getSessionProfiles: (sessionType: "Focus" | "Break" | null) => typedError<SessionProfileDto[], string>(__TAURI_INVOKE("get_session_profiles", { sessionType })),
	/**
	 *  Returns profiles currently active based on their always_on activation rules and the
	 *  current session type from TimerState.
	 */
	getActiveFocusProfiles: () => typedError<FocusProfileDto[], string>(__TAURI_INVOKE("get_active_focus_profiles")),
	/**  Current blocking violation (None if nothing is blocked). */
	getBlockingViolation: () => __TAURI_INVOKE<{
	profileId: number | null,
	profileName: string | null,
	profileColor: string | null,
	blockedTarget: BlockedTargetDto,
} | null>("get_blocking_violation"),
};

/** Events */
export const events = {
	appSettingsChangedEvent: makeEvent<AppSettingsChangedEvent>("app-settings-changed-event"),
	blockingViolationEvent: makeEvent<BlockingViolationEvent>("blocking-violation-event"),
	currentActivityEvent: makeEvent<CurrentActivityEvent>("current-activity-event"),
	inputDetectedEvent: makeEvent<InputDetectedEvent>("input-detected-event"),
	profileChangedEvent: makeEvent<ProfileChangedEvent>("profile-changed-event"),
	sessionChangedEvent: makeEvent<SessionChangedEvent>("session-changed-event"),
	sessionCompletedEvent: makeEvent<SessionCompletedEvent>("session-completed-event"),
	timerUpdatedEvent: makeEvent<TimerUpdatedEvent>("timer-updated-event"),
	updateAvailableEvent: makeEvent<UpdateAvailableEvent>("update-available-event"),
};

/* Types */
/**  Activation mode for a focus profile activation rule. */
export type ActivationMode = "always_on" | "pre_selected";

export type ActivitySettings = {
	/**  Whether to record app usage (app switches) */
	trackApps: boolean,
	/**  Whether to track window changes (not just app switches) */
	trackWindows: boolean,
	/**  Whether to track browser URLs */
	trackBrowser: boolean,
};

/**  An installed application. */
export type App = {
	/**  Unique identifier (same as bundle_id). */
	id: string,
	bundleId: string,
	name: string | null,
	icon: string | null,
	color: string | null,
};

export type AppDistribution = "direct" | "appStore";

/**  App icon payload with optional app display color. */
export type AppIcon = {
	/**  Icon as base64 PNG data URL */
	dataUrl: string | null,
	/**  App display color as hex string like "#5865F2" */
	color: string | null,
};

export type AppInfo = {
	/**  Process ID */
	pid: number,
	/**  Application name (localized) */
	name: string | null,
	/**  Bundle identifier (macOS) */
	bundleId: string | null,
	/**  Path to the executable */
	processPath: string | null,
	/**  App icon payload (only populated if `include_app_icon` is enabled) */
	icon: AppIcon | null,
};

export type AppInfoDto = {
	version: string,
	stage: Stage,
	distribution: AppDistribution,
};

export type AppSettings = {
	version: SettingsVersion,
	launchAtLogin: boolean,
	features: FeaturesSettings,
	appearance: AppearanceSettings,
	audio: AudioSettings,
	developer: DeveloperSettings,
	timer: TimerSettings,
	goals: GoalSettings,
	activity: ActivitySettings,
	focus: FocusSettings,
	cat: CatSettings,
};

export type AppSettingsChangedEvent = AppSettings;

export type AppearanceSettings = {
	theme: Theme,
};

export type AudioChannelSettings = {
	enabled: boolean,
	/**  Volume 0.0..=1.0 (linear scale) */
	volume: number,
};

export type AudioSettings = {
	session: AudioChannelSettings,
	sessionEnd: AudioChannelSettings,
	effects: AudioChannelSettings,
};

/**  Which category and above gets blocked when a focus profile is active. */
export type BlockThreshold = 
/**  Do not block any apps/websites. */
"none" | 
/**  Block only Distracting apps/websites. */
"distracting" | 
/**  Block Neutral and Distracting apps/websites. */
"neutral";

/**  The target that was blocked. */
export type BlockedTargetDto = { type: "app"; bundleId: string } | { type: "website"; domain: string };

/**
 *  Describes what was blocked and by which profile.
 *  Profile fields are None when blocked by threshold with no explicit category assignment.
 */
export type BlockingViolationDto = {
	profileId: number | null,
	profileName: string | null,
	profileColor: string | null,
	blockedTarget: BlockedTargetDto,
};

/**  Event emitted when a blocking violation is detected (or cleared). */
export type BlockingViolationEvent = BlockingViolationDto | null;

export type BrowserInfo = {
	/**  Current URL of the active tab. */
	url: string | null,
	/**
	 *  Bounds of the visible browser content area, when exposed by Accessibility.
	 * 
	 *  This is the visible web content viewport, not the full browser window,
	 *  and may be `None` when the browser does not expose it.
	 */
	contentBounds: WindowBounds | null,
	/**
	 *  Whether the window is in private/incognito mode.
	 * 
	 *  - `None` if detection failed or not supported
	 *  - `Some(true)` if private mode is active
	 *  - `Some(false)` if private mode is not active
	 */
	isPrivate: boolean | null,
	/**  Website information (only populated if `include_website_info` is enabled in config) */
	website: WebsiteInfo | null,
};

export type CatSettings = {
	equippedFur: string,
	equippedFace: string,
	equippedHat: string | null,
};

/**  A category assignment within a focus profile (target + category). */
export type CategoryAssignmentDto = {
	id: number,
	category: FocusCategory,
	target: FocusTargetDto,
};

export type CountdownSettings = {
	durationMinutes: number,
	showSessionSetup: boolean,
};

export type CurrentActivityDto = ({ appActivated: {
	app: AppInfo,
} }) & { windowChanged?: never } | ({ windowChanged: {
	window: WindowInfo,
} }) & { appActivated?: never };

export type CurrentActivityEvent = CurrentActivityDto;

export type CurrentActivityPollTarget = "app" | "window";

export type DeveloperSettings = {
	cat: boolean,
	timerSpeed: number,
};

export type FeaturesSettings = {
	goals: boolean,
	activity: boolean,
	focus: boolean,
	catWindow: boolean,
	developer: boolean,
};

/**  Focus category for an app or website within a profile. */
export type FocusCategory = "focused" | "neutral" | "distracting";

/**
 *  An activation rule for a focus profile.
 *  session_types: None = all session types; Some([...]) = restricted to listed types.
 *  schedule_*: None = no time restriction; Some = AND condition with session_types.
 */
export type FocusProfileActivationDto = {
	id: number,
	mode: ActivationMode,
	sessionTypes: FocusSessionType[] | null,
	scheduleDays: number[] | null,
	scheduleStartTime: string | null,
	scheduleEndTime: string | null,
};

export type FocusProfileActivationParams = {
	mode: ActivationMode,
	sessionTypes: FocusSessionType[] | null,
	scheduleDays: number[] | null,
	scheduleStartTime: string | null,
	scheduleEndTime: string | null,
};

export type FocusProfileCategoryParams = {
	category: FocusCategory,
	target: FocusTargetDto,
};

/**  Focus profile with its category assignments and activation rules. */
export type FocusProfileDto = {
	id: number,
	name: string,
	color: string | null,
	enabled: boolean,
	categories: CategoryAssignmentDto[],
	activations: FocusProfileActivationDto[],
	createdAt: number,
};

/**
 *  Session type for focus profile activation filtering.
 *  Focus = any focus/work session (pomodoro work, progressive work, countdown).
 *  Break = any rest session (pomodoro breaks, progressive break).
 */
export type FocusSessionType = "Focus" | "Break";

export type FocusSettings = {
	blockThreshold: BlockThreshold,
};

/**  The target of a category assignment: all, a specific app, or a specific website. */
export type FocusTargetDto = { type: "all" } | { type: "app"; bundle_id: string; name: string | null; icon: string | null; color: string | null } | { type: "website"; domain: string; name: string | null; icon: string | null; color: string | null };

export type GetCurrentActivityParams = {
	pollTarget: CurrentActivityPollTarget,
};

export type GetWindowActivitiesParams = {
	startedAfter: number,
	startedBefore: number,
	limit: number | null,
};

export type GoalSettings = {
	/**  Daily focus goal in minutes (default: 120 = 2h) */
	dailyGoalMinutes: number,
};

export type GroupMemberDto = { type: "app"; app: App } | { type: "website"; website: Website };

/**  Event emitted when user input is detected (throttled). */
export type InputDetectedEvent = InputType;

/**  Type of input event detected. */
export type InputType = "keyboard" | "mouse";

export type PomodoroSettings = {
	workDurationMinutes: number,
	shortBreakMinutes: number,
	longBreakMinutes: number,
	sessionsBeforeLongBreak: number,
	autoAdvance: boolean,
	autoAdvanceCountdownSeconds: number,
	showSessionSetup: boolean,
};

/**  How a profile was activated for session selection. */
export type ProfileActivation = 
/**  Always-on activation is active, shown in session setup, not removable. */
"always_on" | 
/**  Pre-selected by activation rule, shown in session setup, removable. */
"pre_selected" | 
/**  Manually added by the user. */
"manual";

/**  Event emitted when a focus profile is created, updated, or deleted. */
export type ProfileChangedEvent = null;

export type ProgressivePomodoroSettings = {
	ratings: ProgressiveRatingSetting[],
	autoAdvance: boolean,
	autoAdvanceCountdownSeconds: number,
	showSessionSetup: boolean,
};

export type ProgressiveRatingSetting = {
	key: string,
	label: string,
	description: string,
	suggestions: ProgressiveSuggestion[],
};

export type ProgressiveSessionType = "Work" | "Break";

export type ProgressiveSuggestion = {
	workMinutes: number,
	breakMinutes: number | null,
};

export type SearchParams = {
	/**  Search query */
	query: string,
	/**  Include installed apps (default: true) */
	includeApps?: boolean,
	/**  Include websites (default: true) */
	includeWebsites?: boolean,
	/**  Include icons - slower (default: false) */
	includeIcons?: boolean,
	/**  Maximum results (default: 20) */
	limit: number | null,
};

export type SearchResultDto = { type: "app"; app: App; score: number } | { type: "website"; website: Website; score: number } | { type: "group"; name: string; icon: string | null; members: GroupMemberDto[]; score: number };

/**  Event emitted when session state changes (started, completed, cancelled). */
export type SessionChangedEvent = null;

/**  Event emitted when a session is completed. */
export type SessionCompletedEvent = SessionSummaryDto;

export type SessionDetailDto = {
	id: number,
	sessionType: string,
	status: SessionStatus,
	plannedSeconds: number,
	actualSeconds: number | null,
	intention: string | null,
	startedAt: number,
	endedAt: number | null,
	events: SessionEventDto[],
	stats: SessionStatsDto,
};

export type SessionEventDataDto = {
	seconds: number | null,
};

export type SessionEventDto = {
	eventType: string,
	timestamp: number,
	/**  Extra data (e.g., seconds for Extended events) */
	data: SessionEventDataDto | null,
};

/**  A profile shown in session setup, with how it was activated. */
export type SessionProfileDto = {
	profile: FocusProfileDto,
	activation: ProfileActivation,
};

export type SessionStartInput = {
	intention?: string | null,
	profileIds?: number[] | null,
	blockThreshold?: BlockThreshold | null,
};

/**  Computed stats for a session. */
export type SessionStatsDto = {
	pausedSeconds: number,
	extendedSeconds: number,
	overtimeSeconds: number,
};

export type SessionStatus = "active" | "completed" | "cancelled";

export type SessionSummaryDto = {
	id: number,
	sessionType: string,
	status: SessionStatus,
	plannedSeconds: number,
	actualSeconds: number | null,
	intention: string | null,
	startedAt: number,
	endedAt: number | null,
};

export type SettingsVersion = "0.0.1" | "0.0.2" | "0.0.3";

export type SoundId = "tick" | "complete" | "meow" | "wind-up-tick-1" | "wind-up-tick-2" | "wind-up-tick-3" | "wind-up-tick-4" | "wind-up-tick-5" | "wind-up-tick-6" | "wind-up-tick-7" | "wind-up-tick-8" | "wind-up-tick-9" | "wind-up-tick-10" | "wind-up-tick-11";

export type Stage = "dev" | "prod";

export type Theme = "light" | "dark" | "auto";

export type TimerDto = {
	status: TimerStatus,
	sessionType: string,
	totalSeconds: number,
	remainingSeconds: number,
	overtimeSeconds: number,
	sessionsCompleted: number,
};

export type TimerModeEnum = "pomodoro" | "progressive" | "countdown";

export type TimerSettings = {
	timerMode: TimerModeEnum,
	pomodoro: PomodoroSettings,
	progressive: ProgressivePomodoroSettings,
	countdown: CountdownSettings,
};

export type TimerStatus = "idle" | "running" | "paused";

export type TimerUpdatedEvent = TimerDto;

export type UpdateAvailableEvent = UpdateInfo;

export type UpdateInfo = {
	version: string,
	currentVersion: string,
	/**  Semver parts we are behind (e.g. 1.2.3 → 2.0.0 gives 1, 0, 0). */
	majorBehind: number,
	minorBehind: number,
	patchBehind: number,
};

/**  A website identified by domain. */
export type Website = {
	/**  Unique identifier (same as domain). */
	id: string,
	domain: string,
	name: string | null,
	icon: string | null,
	color: string | null,
};

export type WebsiteInfo = {
	/**  Hostname extracted from the browser URL (e.g., "github.com") */
	hostname: string,
	/**  Favicon as base64 PNG data URL (e.g., "data:image/png;base64,...") */
	favicon: string | null,
	/**  Favicon-derived color as hex string (e.g., "#FF5733") */
	color: string | null,
};

export type WindowActivityDto = {
	appBundleId: string | null,
	appName: string | null,
	appIcon: string | null,
	appColor: string | null,
	websiteDomain: string | null,
	websiteName: string | null,
	websiteIcon: string | null,
	websiteColor: string | null,
	windowTitle: string | null,
	browserUrl: string | null,
	category: string | null,
	startedAt: number,
	endedAt: number,
};

export type WindowBounds = {
	/**  X coordinate (left edge) */
	x: number | null,
	/**  Y coordinate (top edge) */
	y: number | null,
	/**  Window width */
	width: number | null,
	/**  Window height */
	height: number | null,
};

export type WindowInfo = {
	/**  Window title */
	title: string | null,
	/**  Platform-specific window identifier */
	windowId: number | null,
	/**  Window position and size */
	bounds: WindowBounds | null,
	/**  Application information */
	app: AppInfo,
	/**  Browser information (only populated if `include_browser_info` is enabled in config) */
	browser: BrowserInfo | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

